--
-- Table structure for table `DEVICE`
--

DROP TABLE IF EXISTS `DEVICE`;
CREATE TABLE `DEVICE` (
  `UUID` varchar(256) NOT NULL,
  `CATEGORY_ID` varchar(256) NOT NULL,
  `SERIAL_NUMBER` varchar(512) DEFAULT NULL,
  `MODEL` varchar(256) DEFAULT NULL,
  `DESCRIPTION` varchar(512) NOT NULL,
  `VENDOR` varchar(256) DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `WARRANTY_EXPIRY_DATE` date DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ORGANIZATION` varchar(256) DEFAULT NULL,
  `STATUS` varchar(100) DEFAULT 'AVAILABLE',
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `SERIAL_NUMBER` (`SERIAL_NUMBER`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  CONSTRAINT `device_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `DEVICE_CATEGORY` (`UUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `DEVICE_ASSIGNMENT`
--

DROP TABLE IF EXISTS `DEVICE_ASSIGNMENT`;
CREATE TABLE `DEVICE_ASSIGNMENT` (
  `UUID` varchar(256) NOT NULL,
  `DEVICE_ID` varchar(256) NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `EMAIL` varchar(256) NOT NULL,
  `LOCATION` varchar(256) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ORGANIZATION` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `device_assignment_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`UUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `DEVICE_CATEGORY`
--

DROP TABLE IF EXISTS `DEVICE_CATEGORY`;
CREATE TABLE `DEVICE_CATEGORY` (
  `UUID` varchar(256) NOT NULL,
  `NAME` varchar(256) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ORGANIZATION` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `DEVICE_REPAIR`
--

DROP TABLE IF EXISTS `DEVICE_REPAIR`;
CREATE TABLE `DEVICE_REPAIR` (
  `UUID` varchar(256) NOT NULL,
  `DEVICE_ID` varchar(256) NOT NULL,
  `DESCRIPTION` varchar(256) NOT NULL,
  `STATUS` varchar(256) NOT NULL,
  `AGENT` varchar(256) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ORGANIZATION` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `device_repair_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`UUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `DEVICE_STATUS`
--

DROP TABLE IF EXISTS `DEVICE_STATUS`;
CREATE TABLE `DEVICE_STATUS` (
  `UUID` varchar(256) NOT NULL,
  `NAME` varchar(256) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
